color:
  brandColors:
    - '#FFFFFF'
    - '#D2D2D0'
    - '#000000'
    - '#320000'
    - '#5A2F1E'
  brandStrength: 1
  lightness: 0.676535
  rhythmicContrast: 1
  saturation: 0.447368
layout_spectrum: 0.066542
name: High Fashion
typography_spectrum: 0.817982
